#!/bin/bash

# Setup script for Afroverse Mock Mode
# This script configures the app to use dummy data without a server

echo "🎭 Afroverse Mock Mode Setup"
echo "=============================="
echo ""

# Check if we're in the client directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this script from the client directory"
    echo "   cd client && ./setup-mock-mode.sh"
    exit 1
fi

# Create .env.local file
echo "📝 Creating .env.local file..."

cat > .env.local << 'EOF'
# Mock Mode Configuration
# Generated by setup-mock-mode.sh

# Enable Mock Mode (no server required)
VITE_USE_MOCK_DATA=true

# API Configuration (not used in mock mode)
VITE_API_URL=http://localhost:5000/api

# Socket Configuration (not used in mock mode)
VITE_SOCKET_URL=http://localhost:5000

# App Configuration
VITE_APP_NAME=Afroverse
VITE_APP_VERSION=1.0.0
EOF

echo "✅ .env.local created successfully"
echo ""
echo "🎉 Mock Mode is now enabled!"
echo ""
echo "Next steps:"
echo "  1. Start the development server: npm run dev"
echo "  2. Open your browser and navigate the UI"
echo "  3. You'll see '🎭 Mock Mode Enabled' in the console"
echo ""
echo "To disable mock mode:"
echo "  - Edit .env.local and set VITE_USE_MOCK_DATA=false"
echo "  - Or delete .env.local to use default settings"
echo ""
echo "📚 See MOCK_MODE_GUIDE.md for more information"
echo ""

