@echo off
REM Setup script for Afroverse Mock Mode (Windows)
REM This script configures the app to use dummy data without a server

echo.
echo 🎭 Afroverse Mock Mode Setup
echo ==============================
echo.

REM Check if we're in the client directory
if not exist "package.json" (
    echo ❌ Error: Please run this script from the client directory
    echo    cd client ^&^& setup-mock-mode.bat
    exit /b 1
)

REM Create .env.local file
echo 📝 Creating .env.local file...

(
echo # Mock Mode Configuration
echo # Generated by setup-mock-mode.bat
echo.
echo # Enable Mock Mode ^(no server required^)
echo VITE_USE_MOCK_DATA=true
echo.
echo # API Configuration ^(not used in mock mode^)
echo VITE_API_URL=http://localhost:5000/api
echo.
echo # Socket Configuration ^(not used in mock mode^)
echo VITE_SOCKET_URL=http://localhost:5000
echo.
echo # App Configuration
echo VITE_APP_NAME=Afroverse
echo VITE_APP_VERSION=1.0.0
) > .env.local

echo ✅ .env.local created successfully
echo.
echo 🎉 Mock Mode is now enabled!
echo.
echo Next steps:
echo   1. Start the development server: npm run dev
echo   2. Open your browser and navigate the UI
echo   3. You'll see '🎭 Mock Mode Enabled' in the console
echo.
echo To disable mock mode:
echo   - Edit .env.local and set VITE_USE_MOCK_DATA=false
echo   - Or delete .env.local to use default settings
echo.
echo 📚 See MOCK_MODE_GUIDE.md for more information
echo.

